// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RgFWFtnq38L7cVF6QvLI23LPveUSiEU',
    appId: '1:1033531870512:web:787434c20107bafdd74cf5',
    messagingSenderId: '1033531870512',
    projectId: 'prime-okgroup',
    authDomain: 'prime-okgroup.firebaseapp.com',
    storageBucket: 'prime-okgroup.firebasestorage.app',
    measurementId: 'G-HN4M8ETTPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDLF20OM3WKsOGz-ca5VRPfFpU_wY3StI',
    appId: '1:1033531870512:android:35fda2e2ef1a0524d74cf5',
    messagingSenderId: '1033531870512',
    projectId: 'prime-okgroup',
    storageBucket: 'prime-okgroup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Qnn-mVhYI-5iz6nTlk5IkzpYbIRbJMY',
    appId: '1:1033531870512:ios:88a2edeca4c5c322d74cf5',
    messagingSenderId: '1033531870512',
    projectId: 'prime-okgroup',
    storageBucket: 'prime-okgroup.firebasestorage.app',
    iosClientId: '1033531870512-j312goh92ad1d6jjcd7rfvvh1g2j1bin.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaultly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Qnn-mVhYI-5iz6nTlk5IkzpYbIRbJMY',
    appId: '1:1033531870512:ios:88a2edeca4c5c322d74cf5',
    messagingSenderId: '1033531870512',
    projectId: 'prime-okgroup',
    storageBucket: 'prime-okgroup.firebasestorage.app',
    iosClientId: '1033531870512-j312goh92ad1d6jjcd7rfvvh1g2j1bin.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaultly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_RgFWFtnq38L7cVF6QvLI23LPveUSiEU',
    appId: '1:1033531870512:web:960be0c7a17845ecd74cf5',
    messagingSenderId: '1033531870512',
    projectId: 'prime-okgroup',
    authDomain: 'prime-okgroup.firebaseapp.com',
    storageBucket: 'prime-okgroup.firebasestorage.app',
    measurementId: 'G-5YPLTKKDTG',
  );
}
